language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t matt.bliese/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matt.bliese/docker-react npm run test